import Sidebar from "@/components/Sidebar";
import { Box, Heading } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const ProductPage = () => {
	const url = useRouter();
	console.log(url);

	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Sidebar />
			<Box
				ml={"15vw"}
				width={"85vw"}
				height={"100vh"}
				maxHeight={"100vh"}
				p={8}
			>
				<Box>
					<Heading pb={8}>All Product</Heading>
				</Box>
			</Box>
		</>
	);
};

export default ProductPage;
