import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import {
	Box,
	Flex,
	Grid,
	GridItem,
	HStack,
	Heading,
	Stack,
} from "@chakra-ui/react";
import BestProduct from "@/components/Dashboard/BestProduct";
import IncomeThisMonthCard from "@/components/Dashboard/IncomeThisMonth";
import BalanceCard from "@/components/Dashboard/BalanceCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Sidebar />
			<Box
				ml={"15vw"}
				width={"85vw"}
				height={"100vh"}
				maxHeight={"100vh"}
				p={8}
			>
				<Box>
					<Heading pb={8}>Top Product</Heading>
					<Grid
						h={250}
						templateRows="repeat(2, 1fr)"
						templateColumns="repeat(4, 1fr)"
						gap={4}
					>
						<GridItem rowSpan={1} colSpan={2}>
							<BestProduct />
						</GridItem>
						<GridItem rowSpan={1} colSpan={1}>
							<IncomeThisMonthCard />
						</GridItem>
						<GridItem rowSpan={1} colSpan={1}>
							<BalanceCard />
						</GridItem>
					</Grid>
				</Box>
			</Box>
		</>
	);
}
